import { MenuItem } from "@/types";

export const siteMetadata = {
  title: "Rayan Kazi",
  description: "University student, software engineer, passionate builder",
  url: "https://rayankazi.dev",
};

export const menuItems: MenuItem[] = [
  {
    href: "/",
    name: "Home",
  },
  {
    href: "/#connect",
    name: "Contact",
  },
  {
    href: "/blog",
    name: "Blog",
  },
  {
    href: "/projects",
    name: "Projects",
  },
  {
    href: "/experience",
    name: "Experience",
  },
];

export const experienceData = [
  {
    time: "Aug 2024 - May 2025",
    place: "Grand Canyon University",
    position: "Research Intern",
    shortDescription:
      "Research Intern. Investigating how humans can detect phishing emails generated by commercial LLMs.",
    longBullets: [
      "Investigated how humans detect AI-generated phishing emails and whether detection rate depends on the LLM used; tested models were GPT, Claude, or Gemini",
      "Found that human detection rate of AI emails to be 60; also discovered insignificant relationship between LLM used to generate email and human detection rate",
      "Presented findings in 5000 word research paper and 20 minute presentation given to multiple crowds",
    ],
  },
  {
    time: "Jun 2024 - Dec 2024",
    place: "We Care Act NYC",
    position: "IT Member",
    shortDescription:
      "SWE Intern. Developed new CRM for college consulting subsidiary and did general maintenance for main organization website.",
    longBullets: [
      "Maintain EcoAccess website used by 500+ students and donors with Next JS and Tailwind",
      "Implemented over 5 key features in new CRM for college consulting subsidiary of organization",
      "Led development of organization internal tool to track 50+ donation and student computer requests daily",
    ],
  },
  {
    time: "Jun 2023 - Aug 2023",
    place: "SitePoint",
    position: "Guest Author",
    longBullets: [
      "Pitched, wrote, and published articles related to web development, reaching 10,000+ developers",
      "Generated significant developer engagement, with articles attaining trending status",
      "Collaborated with the SitePoint editorial team to align content with their SEO strategy, contributing to the overall growth of their course platform's visibility",
    ],
  },
];
