import { MenuItem, ProjectItem } from "@/types";

export const siteMetadata = {
  title: "Rayan Kazi",
  description: "University student, software engineer, passionate builder",
  url: "https://rayankazi.dev",
};

export const menuItems: MenuItem[] = [
  {
    href: "/",
    name: "Home",
  },
  {
    href: "/#connect",
    name: "Contact",
  },
  {
    href: "/blog",
    name: "Blog",
  },
  {
    href: "/projects",
    name: "Projects",
  },
  {
    href: "/experience",
    name: "Experience",
  },
  {
    href: "/notes",
    name: "Notes",
  },
];

export const projectsData: ProjectItem[] = [
  {
    title: "Immerse",
    description: "A chrome extension for minimizing student distractions",
    image: {
      url: "/images/projects/immerse-preview.png",
      alt: "An screenshot of Immerse app",
    },
    href: "/projects/immerse",
  },
  {
    title: "Taskmaster",
    description: "An all-in-one task management tool. For everyone",
    image: {
      url: "/images/projects/taskmaster-preview.png",
      alt: "An screenshot of Taskmaster app",
    },
    href: "/projects/taskmaster",
  },
];

export const experienceData = [
  {
    time: "Mar 2025 - Current",
    place: "Career Chats",
    position: "National Officer",
    shortDescription:
      "National Officer. Conducting interviews with CS professionals and developing guides for high schoolers interested in AI.",
    longBullets: [
      "Conducting interviews with CS professionals to gain career insights",
      "Developed 20 page field guide on how high schoolers can get started with AI/ML",
    ],
  },
  {
    time: "Aug 2024 - Current",
    place: "Grand Canyon University",
    position: "Independent Researcher",
    shortDescription:
      "Independent Researcher. Investigating how humans can detect phishing emails generated by commercial LLMs.",
    longBullets: [
      "Looking at the rate at which humans can detect AI-generated phishing emails and whether the detection rate depends on the LLM used",
      "Models tested were GPT-4o, Claude 3.7 Sonnet, and Gemini 2.0 Flash",
      // TODO: add stuff about findings of research
      "Presented findings in 5000 word research paper and 20 minute presentation given to multiple crowds",
    ],
  },
  {
    time: "Jun 2024 - Current",
    place: "We Care Act NYC",
    position: "IT Member",
    shortDescription:
      "Developed new CRM for college consulting subsidiary and maintaining current We Care Act website.",
    longBullets: [
      "Develop and maintain EcoAccess website used by 100s of students and donators with Next JS and Tailwind",
      "Implement over 5 key features in new CRM for college consulting subsidiary",
      "Led development of internal project for tracking 50+ donation and student computer requests",
    ],
  },
  {
    time: "Jun 2023 - Aug 2023",
    place: "SitePoint",
    position: "Guest Author",
    longBullets: [
      "Produced articles on JavaScript, Next JS, and other web development technology read by over 10,000 developers",
      "Integrated SEO best practices on SitePoint blog to promote course platform",
    ],
  },
];

export const notesMetadata = [
  {
    title: "Test Note",
    href: "/notes/test-note",
    date: "04/01/2025",
  },
];
