export const personalInfo = {
  name: {
    first: "Rayan",
    last: "Kazi",
  },
  title: "Software Engineer",
  description: "University student, software engineer, passionate builder.",
  location: "Phoenix, AZ",
  availability: {
    status: "Available for work",
    isAvailable: true,
  },
  email: "rkazi1@asu.edu",
  portfolioYear: new Date().getFullYear().toString(),
};

export const currentWork = {
  role: "CS Student",
  company: "ASU",
  startYear: "2025",
  endYear: "Present",
};

export const skills = [
  "Next JS",
  "Tailwind CSS",
  "Python",
  "TypeScript",
  "Databases",
];

export const workExperience = [
  {
    year: "Aug 2024 - May 2025",
    role: "Research Intern",
    company: "Grand Canyon University",
    description:
      "Investigated how humans can detect phishing emails generated by commercial LLMs.",
  },
  {
    year: "Jun 2024 - Dec 2024",
    role: "Software Engineering Intern",
    company: "We Care Act NYC",
    description:
      "Developed new CRM for college consulting subsidiary and did general maintenance for primary organization website.",
  },
  {
    year: "Jun 2023 - Aug 2023",
    role: "Content Intern",
    company: "SitePoint",
    description:
      "Pitched, wrote, and published articles related to web development",
  },
];

export const education = [
  {
    year: "2029",
    degree: "Bachelor of Science, Computer Science",
    university: "Arizona State University",
    // status: "Graduated",
    description: "Concentration - Software Engineering",
    additionalInfo: "Attended Barrett, the Honors College",
  },
];

export const blogPosts = [
  {
    title: "The Future of Web Development",
    excerpt:
      "Exploring how AI and automation are reshaping the way we build for the web.",
    date: "Dec 2024",
    readTime: "5 min",
    url: "#", // Add actual URL when available
  },
  {
    title: "Design Systems at Scale",
    excerpt:
      "Lessons learned from building and maintaining design systems across multiple products.",
    date: "Nov 2024",
    readTime: "8 min",
    url: "#",
  },
  {
    title: "Performance-First Development",
    excerpt:
      "Why performance should be a first-class citizen in your development workflow.",
    date: "Oct 2024",
    readTime: "6 min",
    url: "#",
  },
  {
    title: "The Art of Code Review",
    excerpt:
      "Building better software through thoughtful and constructive code reviews.",
    date: "Sep 2024",
    readTime: "4 min",
    url: "#",
  },
];

export const socialLinks = [
  { name: "GitHub", handle: "@rayankzi", url: "https://github.com/rayankzi" },
  // { name: "v0.dev", handle: "@felixmacaspac", url: "#" },
  // { name: "HubSpot Community", handle: "@felixmacaspac", url: "" },
  {
    name: "LinkedIn",
    handle: "rayan-kazi-dev",
    url: "https://www.linkedin.com/in/rayan-kazi-dev/",
  },
];

export const footer = {
  copyright: "© 2025 Rayan Kazi. All rights reserved.",
  builtWith: "Built with ❤️ by Rayan Kazi",
};

// Date ranges for sections
export const dateRanges = {
  work: "2023 — 2025",
};

export const projects = [
  {
    title: "Design System Library",
    description:
      "A comprehensive component library built with React and TypeScript, featuring 50+ accessible components.",
    date: "2024",
    thumbnail: "/placeholder.svg?height=400&width=600",
  },
  {
    title: "AI Content Generator",
    description:
      "Machine learning powered tool that generates marketing copy and blog content using GPT-4.",
    date: "2024",
    thumbnail: "/placeholder.svg?height=400&width=600",
  },
  {
    title: "E-commerce Dashboard",
    description:
      "Real-time analytics dashboard for online stores with sales tracking and inventory management.",
    date: "2023",
    thumbnail: "/placeholder.svg?height=400&width=600",
  },
  {
    title: "Task Management App",
    description:
      "Collaborative project management tool with drag-and-drop kanban boards and team features.",
    date: "2023",
    thumbnail: "/placeholder.svg?height=400&width=600",
  },
];
